name: Workflow2
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Version Composition
        id: composer
        uses: juliansangillo/version-composer@v1
        with:
          revision-pattern: M.m.b.p

      - name: Version Orchestration
        uses: juliansangillo/version-maestro@v1
        with:
          version: ${{ steps.composer.outputs.version }}
          env: 
            SRC: src
            SRC_UTILS: src/utils
            shell: bash
        
        run: version-maestro ${{ inputs.version }} ${{ inputs.revision-pattern }} ${{ inputs.preferred-type }}